
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: resort
spec:
  ca:
    secretName: ca-key-pair
---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: casigned-cert
  namespace: resort
spec:
  commonName: resort.app.openkube.io
  secretName: casigned-cert-tls
  issuerRef:
    name: ca-issuer
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: resort-ingress
  namespace: resort
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts: 
    - resort.app.openkube.io
    secretName: casigned-cert-tls
  rules:
  - host: resort.app.openkube.io
    http:
      paths:
      - path: /
        backend:
          serviceName: resort-svc
          servicePort: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resort
  namespace: resort
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resort
  template:
    metadata:
      labels:
        app: resort
    spec:
      containers:
      - name: resort
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: resort-svc
  namespace: resort
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: resort